name: yomu
description: "Yomu is a free book + audiobook reader for everyone."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.9
  google_fonts: ^6.1.0
  just_audio: ^0.9.36
  animations: ^2.1.1
  cached_network_image: ^3.3.0
  file_picker: ^8.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  epubx: ^4.0.0
  path_provider: ^2.1.2
  http: ^1.6.0
  permission_handler: ^12.0.1
  device_info_plus: ^12.3.0
  epub_view: ^3.2.0
  intl: ^0.20.2
  pdfrx: ^1.3.5
  shared_preferences: ^2.2.2
  flutter_html: ^3.0.0-beta.2
  flutter_animate: ^4.5.2
  collection: ^1.18.0
  webview_flutter: ^4.13.1
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
      ref: 2cea396843cd3ab1b5ec4334be4233864637874e
  crypto: ^3.0.7
  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/
